// <auto-generated />
namespace Review_Site.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ResourceDateAddedChange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ResourceDateAddedChange));
        
        string IMigrationMetadata.Id
        {
            get { return "201302282131295_ResourceDateAddedChange"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
