// <auto-generated />
namespace Review_Site.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class PageHits : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PageHits));
        
        string IMigrationMetadata.Id
        {
            get { return "201301152350336_PageHits"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
