// <auto-generated />
namespace Review_Site.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class FixColor : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixColor));
        
        string IMigrationMetadata.Id
        {
            get { return "201301141705587_Fix-Color"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
